cleanup when done

diff --git a/dev-utilities/committer-utils/metron-committer-common b/dev-utilities/committer-utils/metron-committer-common
--- a/dev-utilities/committer-utils/metron-committer-common
+++ b/dev-utilities/committer-utils/metron-committer-common
@@ -350,6 +350,7 @@ function run_tests {
         echo
         if [[ $REPLY =~ ^[Yy]$ ]]; then
             run_bro_docker
+            finish_bro_docker
         else
             echo "  when you are ready and the containers are stopped, please cd into the docker"
             echo "  directory and execute the run_end_to_end.sh script"
@@ -454,7 +455,22 @@ function run_bro_docker {
         echo "ERROR> FAILED run_end_to_end"
         exit ${rc}
     fi
+    cd .. &> /dev/null || { echo "failed to change directory to plugin root"; exit 1; }
+}
 
+#
+#   runs the finish bro docker script to cleanup
+#
+function finish_bro_docker {
+    cd docker &> /dev/null || { echo "failed to change directory to docker"; exit 1; }
+    ./finish_end_to_end.sh
+
+    rc=$?; if [[ ${rc} != 0 ]]; then
+        echo "ERROR> FAILED run_end_to_end"
+        exit ${rc}
+    fi
+    cd .. &> /dev/null || { echo "failed to change directory to plugin root";
+        exit 1; }
 }
 
 #
