refactored per review

diff --git a/dev-utilities/committer-utils/metron-committer-common b/dev-utilities/committer-utils/metron-committer-common
--- a/dev-utilities/committer-utils/metron-committer-common
+++ b/dev-utilities/committer-utils/metron-committer-common
@@ -192,7 +192,7 @@ function setup_code {
         # clone the repository and fetch updates
         mkdir -p ${WORK}
         git clone ${ORIGIN} ${WORK}
-        cd ${WORK} || exit 1
+        cd ${WORK} &> /dev/null || echo "failed to change directory to ${WORK}" && exit 1
 
         # setup the git user and email for your apache account
         git config user.name "$APACHE_NAME"
@@ -229,7 +229,7 @@ function setup_code {
 
     PR_BRANCH_REF="pull/$PR/head:pr-$PR"
     PR_BRANCH="pr-$PR"
-    cd ${WORK} || exit 1
+    cd ${WORK} &> /dev/null || echo "failed to change directory to ${WORK}" && exit 1
     git fetch ${GITHUB_REMOTE} ${PR_BRANCH_REF}
     echo ""
 }
@@ -316,8 +316,6 @@ function commit {
 #
 function review_commit_info {
     # review the commit
-    echo ""
-    echo ""
     git diff --stat --color "upstream/$BASE_BRANCH..$BASE_BRANCH"
     echo ""
     echo ""
@@ -328,8 +326,6 @@ function review_commit_info {
 # Runs the metron unit, integration and metron-interface tests
 #
 function run_tests {
-    echo ""
-    echo ""
     read -p "  run test suite? [yN] " -n 1 -r
     echo
     if [[ $REPLY =~ ^[Yy]$ ]]; then
@@ -358,8 +354,6 @@ function run_tests {
 # Cleans the metron src and rpms
 #
 function clean_metron_src {
-    echo ""
-    echo ""
 
     mvn -q clean
 
@@ -368,7 +362,7 @@ function clean_metron_src {
         exit ${rc}
     fi
 
-    cd metron-deployment || exit 1
+    cd metron-deployment &> /dev/null || echo "failed to change directory to metron-deployment" && exit 1
 
     mvn -q clean -Pbuild-rpms
 
@@ -377,7 +371,7 @@ function clean_metron_src {
         exit ${rc}
     fi
 
-    cd .. || exit 1
+    cd .. &> /dev/null || echo "failed to change directory to metron source root" && exit 1
 }
 
 #
@@ -430,7 +424,7 @@ function run_mvn_ui_tests {
 # runs the mvn rpm build
 #
 function run_mvn_build_rpms {
-    cd metron-deployment || exit 1
+    cd metron-deployment &> /dev/null || echo "failed to change directory to metron-deployment" && exit 1
 
     mvn -q package -Pbuild-rpms
 
