Updating rc check script to align with seperators and KEYS file

diff --git a/dev-utilities/release-utils/metron-rc-check b/dev-utilities/release-utils/metron-rc-check
--- a/dev-utilities/release-utils/metron-rc-check
+++ b/dev-utilities/release-utils/metron-rc-check
@@ -30,7 +30,9 @@ function help {
   echo " "
 }
 
-METRON_DIST="https://dist.apache.org/repos/dist/dev/metron/"
+APACHE_REPO="https://dist.apache.org/repos/dist/"
+METRON_DIST=${APACHE_REPO}"dev/metron/"
+METRON_KEYS=${APACHE_REPO}"release/metron/KEYS"
 # print help, if the user just runs this without any args
 if [ "$#" -eq 0 ]; then
     help
@@ -156,14 +158,13 @@ if [ ! -d "$WORK" ]; then
 fi
 echo "Working directory $WORK"
 
-KEYS="$METRON_RC_DIST/KEYS"
-METRON_ASSEMBLY="$METRON_RC_DIST/apache-metron-$METRON_VERSION-$RC.tar.gz"
+METRON_ASSEMBLY="$METRON_RC_DIST/apache-metron_$METRON_VERSION-$RC.tar.gz"
 METRON_ASSEMBLY_SIG="$METRON_ASSEMBLY.asc"
 
 
-echo "Downloading $KEYS"
-if ! wget -P "$WORK" "$KEYS" ; then
-  echo "[ERROR] Failed to download $KEYS"
+echo "Downloading $METRON_KEYS"
+if ! wget -P "$WORK" "$METRON_KEYS" ; then
+  echo "[ERROR] Failed to download $METRON_KEYS"
   exit 1
 fi
 
@@ -206,7 +207,7 @@ if ! gpg --import KEYS ; then
 fi
 
 echo "Verifying Metron Assembly"
-if ! gpg --verify ./"apache-metron-$METRON_VERSION-$RC.tar.gz.asc" "apache-metron-$METRON_VERSION-$RC.tar.gz" ; then
+if ! gpg --verify ./"apache-metron_$METRON_VERSION-$RC.tar.gz.asc" "apache-metron_$METRON_VERSION-$RC.tar.gz" ; then
   echo "[ERROR] failed to verify Metron Assembly"
   exit 1
 fi
@@ -227,7 +228,7 @@ if [ -n "$BRO" ]; then
 fi
 
 echo "Unpacking Assemblies"
-if ! tar -xzf "apache-metron-$METRON_VERSION-$RC.tar.gz" ; then
+if ! tar -xzf "apache-metron_$METRON_VERSION-$RC.tar.gz" ; then
   echo "[ERROR] failed to unpack Metron Assembly"
   exit 1
 fi
